{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.21"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.3.2.jar",
          "url": "spring-boot-buildpack-platform-3.3.2.jar",
          "size": 289039,
          "sha512": "8dce78210e86b5b4e36dcabee3f8daf6f0c2af84ee62aef273a36ec708ac6d5d033a5bcb25a14b301089d4171a3e56297f4a9c247e2a22f911463ae35dd86e12",
          "sha256": "ef1711217215ef72d6af590ba7c3056f4b32ae91f72809aa6e703fd9a9fac96f",
          "sha1": "24a4a099f35c97f14b40c350ef106e9b59ffb618",
          "md5": "619e534a5c5cdf1afe88754126fe0b1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.21"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.3.2.jar",
          "url": "spring-boot-buildpack-platform-3.3.2.jar",
          "size": 289039,
          "sha512": "8dce78210e86b5b4e36dcabee3f8daf6f0c2af84ee62aef273a36ec708ac6d5d033a5bcb25a14b301089d4171a3e56297f4a9c247e2a22f911463ae35dd86e12",
          "sha256": "ef1711217215ef72d6af590ba7c3056f4b32ae91f72809aa6e703fd9a9fac96f",
          "sha1": "24a4a099f35c97f14b40c350ef106e9b59ffb618",
          "md5": "619e534a5c5cdf1afe88754126fe0b1a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.3.2-javadoc.jar",
          "url": "spring-boot-buildpack-platform-3.3.2-javadoc.jar",
          "size": 417608,
          "sha512": "ccad11da2c55926fd2d5680e7df4656f962e167131de19e6431fd0e5ecc1855db99925a59ffb6e7c3763ed3a68eaab4ffd29e255db5b8795826ae3eb74a03735",
          "sha256": "b53861bc23f9fe93d8b5d957c911ba1830f909c7570a9488318c68914ee90b15",
          "sha1": "d46831be1e9ba4faae4199b1fccd8c669f505acc",
          "md5": "a5a40f8288b4e218621e3313e18e5079"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.3.2-sources.jar",
          "url": "spring-boot-buildpack-platform-3.3.2-sources.jar",
          "size": 177580,
          "sha512": "8198a08d69ff2894b1ccea0aefec2a2d8202299c276bb2771b4f3e880a649b92ff665e3ee379be0b4df9cc5f735c298e99f083409e7f428c625b017d6b8a4989",
          "sha256": "8065f77a3f2ced6de238e2a20b590c4b1517df860f57b22b15e85c9da76d3c78",
          "sha1": "8d5056c1b597788047d886b4b4775506f59ce8bb",
          "md5": "bb2da195ddc867602a248091c99f8de1"
        }
      ]
    }
  ]
}
