{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.3.2.jar",
          "url": "spring-boot-starter-3.3.2.jar",
          "size": 4768,
          "sha512": "4e4ae6e7549a600219ed2d12ad65b08fb7a0fff0ca24fb1ac1320d7d487715c3ecb26c39cabc274e5b09052b9efb0f0c6c116e98a521267288f7fbf4fd98f6a1",
          "sha256": "26e9c2eb823b753d58df26eed2fe8222e6f88fa714b4876e3a7327cb826bfe29",
          "sha1": "f9377a223dab5c4afe7aead05bf6ac567cf565ab",
          "md5": "1a484a738acb71e500d57cdbccf94923"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.3.2.jar",
          "url": "spring-boot-starter-3.3.2.jar",
          "size": 4768,
          "sha512": "4e4ae6e7549a600219ed2d12ad65b08fb7a0fff0ca24fb1ac1320d7d487715c3ecb26c39cabc274e5b09052b9efb0f0c6c116e98a521267288f7fbf4fd98f6a1",
          "sha256": "26e9c2eb823b753d58df26eed2fe8222e6f88fa714b4876e3a7327cb826bfe29",
          "sha1": "f9377a223dab5c4afe7aead05bf6ac567cf565ab",
          "md5": "1a484a738acb71e500d57cdbccf94923"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.3.2-javadoc.jar",
          "url": "spring-boot-starter-3.3.2-javadoc.jar",
          "size": 4734,
          "sha512": "13a67d9c0beb41c8ec5b54f1ca4d8c42bb5bc8953aa9b895a8083d6344bb5366d65be00b6f95d60eab669623a1781f35cd208f54d41feaea1d2860615f3e686b",
          "sha256": "01e3153d6d87ae5d386ce8e209146768410049a873241d90e1b84e455453ba5d",
          "sha1": "42491febe2434b8dab3ebed8b953e0db03f5732e",
          "md5": "e01eeb781bb78dc47f6b6ad4b3730103"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.3.2-sources.jar",
          "url": "spring-boot-starter-3.3.2-sources.jar",
          "size": 4734,
          "sha512": "abb09f9576d5f38900ab1ad518cc0ae461a8722ad8c0747da973da5963f24804ece5af51a08d27fe9002cbbcf1b6c150fbd5bebd16b22862a849e2eecb18df1d",
          "sha256": "a9a0d5ed1c14a48ad8c72807d4ff13b680b16639c25eaad9a17c931af0b15974",
          "sha1": "5054d5de17fac339ae267456071eb58210e33bf7",
          "md5": "8ddd40ba000034fd4e86a62fa374a9af"
        }
      ]
    }
  ]
}
