{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.3.2.jar",
          "url": "spring-boot-starter-logging-3.3.2.jar",
          "size": 4760,
          "sha512": "5a94683fbe5a0cdfe344bc78d0dde0a3d64fc5ce81b6ecd22427d57f9e519e41ef56eef5fbeded6c5236e6bc183156ce5791c2226c3d8c43958abd558739f528",
          "sha256": "c9bed9a694d786679afb3944ec5296d367bab8f5f571b733073457bda643e901",
          "sha1": "b685c97f3c24dc30c53ae18151a798f701f2a640",
          "md5": "e1018b91ccda856441b4c2fc29bf3223"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.3.2.jar",
          "url": "spring-boot-starter-logging-3.3.2.jar",
          "size": 4760,
          "sha512": "5a94683fbe5a0cdfe344bc78d0dde0a3d64fc5ce81b6ecd22427d57f9e519e41ef56eef5fbeded6c5236e6bc183156ce5791c2226c3d8c43958abd558739f528",
          "sha256": "c9bed9a694d786679afb3944ec5296d367bab8f5f571b733073457bda643e901",
          "sha1": "b685c97f3c24dc30c53ae18151a798f701f2a640",
          "md5": "e1018b91ccda856441b4c2fc29bf3223"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.3.2-javadoc.jar",
          "url": "spring-boot-starter-logging-3.3.2-javadoc.jar",
          "size": 4743,
          "sha512": "cbff29dd04f085439384b55304b3d5462b01a5eeae22e6eb290e4d39ce95f16a3b5a4873c1c87542fc58b44e3a5c7247c699ead233e0ee48c4b23bd903e5095d",
          "sha256": "263ecab5f20fc506784814580ad47c98373db42126fdfaae2aa09b9a2ff18f59",
          "sha1": "7811f439e72824475355e51c72f701eed699674b",
          "md5": "00f0c9940d238300f98daddca8de9b15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.3.2-sources.jar",
          "url": "spring-boot-starter-logging-3.3.2-sources.jar",
          "size": 4743,
          "sha512": "15f0242cf4c3ed09248c88e35893254a3b9321db8a1021c63b43e4db60a9a2e638d739e97c526ecdfd480a20e5bbfccd4d6eca18169a8dc69ef16f040214a82d",
          "sha256": "41246d9fb9b586a6f6e6427c3295d513f285b670de77f7aca6e978fd459974f3",
          "sha1": "2af22779bac2db5801e95bb8af91ca594bba7d34",
          "md5": "7b577224dda6d64a1f481b3e6d04e9f3"
        }
      ]
    }
  ]
}
