{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.3.2.jar",
          "url": "spring-boot-loader-tools-3.3.2.jar",
          "size": 458440,
          "sha512": "bd3a4af15e3ff702c5e4c29b7fa962eae55d9bf478684b4b9ba2edbf61164141c918ee5052b09af6307883c5be3efd0b6050b486c77fd7032ba79aa970e2a508",
          "sha256": "9449f6831d3d9abf79568d23283c50e6044579c12e9e3fd9cd126b916d31cfe3",
          "sha1": "1fbf32e3b988b86fba47cc799ac2fcda623c9986",
          "md5": "79dc09df9c34b2a587c4bbee536f06be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.3.2.jar",
          "url": "spring-boot-loader-tools-3.3.2.jar",
          "size": 458440,
          "sha512": "bd3a4af15e3ff702c5e4c29b7fa962eae55d9bf478684b4b9ba2edbf61164141c918ee5052b09af6307883c5be3efd0b6050b486c77fd7032ba79aa970e2a508",
          "sha256": "9449f6831d3d9abf79568d23283c50e6044579c12e9e3fd9cd126b916d31cfe3",
          "sha1": "1fbf32e3b988b86fba47cc799ac2fcda623c9986",
          "md5": "79dc09df9c34b2a587c4bbee536f06be"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.3.2-javadoc.jar",
          "url": "spring-boot-loader-tools-3.3.2-javadoc.jar",
          "size": 250978,
          "sha512": "fc68341c4304d4888e08fbe9d4083dfb7a9e6873300f520c81c657f9abfa1b0473cb613f50dc4001dd78ec5c4a9353de72b8bdfc027a0ed7ce7d4e9ef537e35b",
          "sha256": "1d746077bfabdb78c6fa77ffcec93104cfeab38b1cc4e883817bd89acb4b210a",
          "sha1": "9f429c84bd7c54f35a9370485babbc4f08c67254",
          "md5": "ced8807ef028399b9720882a0dc25665"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.3.2-sources.jar",
          "url": "spring-boot-loader-tools-3.3.2-sources.jar",
          "size": 75052,
          "sha512": "8fe57d948d8c9d251250db83441ed5cd133b9827d85c3a6a2bc37cfd19cb8932ce37e8d1986dc16f5976eee7467f9ade031ad08283f16f50a803a81aeeceddce",
          "sha256": "e4b58c3070c794d1e1414e12e721deaad594ebce39c67632aadfca0962d8819e",
          "sha1": "d8c5849965f47b3f62630b1cd5f7b477ef6295db",
          "md5": "25afbb70c3be4afea0f6f5e51e21260c"
        }
      ]
    }
  ]
}
