{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "6.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.1.11.jar",
          "url": "spring-aop-6.1.11.jar",
          "size": 417100,
          "sha512": "b18319cb3b670e1852777ff429de44db358587f266d1f7005e5739b5d2cc794b8d5fdf92c4df2501ae8da7605bbb6995f9d1175551df7eb281115e85803ed16e",
          "sha256": "816e36970a2c75dca5721cc052d5fb5202df459f923bd0c27ec4f013371a6f6d",
          "sha1": "3503ef99b759b81f8b0b3d5260bf4842e393a581",
          "md5": "209d4c6d658a566b2945a8b2bec9a39d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.11"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.1.11.jar",
          "url": "spring-aop-6.1.11.jar",
          "size": 417100,
          "sha512": "b18319cb3b670e1852777ff429de44db358587f266d1f7005e5739b5d2cc794b8d5fdf92c4df2501ae8da7605bbb6995f9d1175551df7eb281115e85803ed16e",
          "sha256": "816e36970a2c75dca5721cc052d5fb5202df459f923bd0c27ec4f013371a6f6d",
          "sha1": "3503ef99b759b81f8b0b3d5260bf4842e393a581",
          "md5": "209d4c6d658a566b2945a8b2bec9a39d"
        }
      ]
    }
  ]
}
