{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.3.2.jar",
          "url": "spring-boot-test-3.3.2.jar",
          "size": 249163,
          "sha512": "e7fe6932da053eaf3c230910e2827dabb7f5278e16a431332036a97fa9ef0ed2c2101162c66284d307104c0b65e459574a1f06433705b986191ebfc4b31d7d57",
          "sha256": "0f56e30d35bd7505f9968ba89a3515210d8dbd4ec07512bb7d71d872697e3a73",
          "sha1": "65d63a6516482fcd70e65a3c0fa1e6ca0f3a29a3",
          "md5": "86ee9df23734b4197a4d27af3da0734b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.3.2.jar",
          "url": "spring-boot-test-3.3.2.jar",
          "size": 249163,
          "sha512": "e7fe6932da053eaf3c230910e2827dabb7f5278e16a431332036a97fa9ef0ed2c2101162c66284d307104c0b65e459574a1f06433705b986191ebfc4b31d7d57",
          "sha256": "0f56e30d35bd7505f9968ba89a3515210d8dbd4ec07512bb7d71d872697e3a73",
          "sha1": "65d63a6516482fcd70e65a3c0fa1e6ca0f3a29a3",
          "md5": "86ee9df23734b4197a4d27af3da0734b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.3.2-javadoc.jar",
          "url": "spring-boot-test-3.3.2-javadoc.jar",
          "size": 413952,
          "sha512": "4f54cb879135d4295aef60804d3ab60f4445c97ac98fa934a6e7aade58f295f19e20f3e1499c4994d1914143359bd304716d9d1567e35b2fcbff3fd44b92528f",
          "sha256": "cb6671d3950b36c64caadd95f84bcfad24c2e6aab830aa59a611f2a590bee811",
          "sha1": "d0579ab8ca7ebb1f84ddde25e8ad6ef9cd310969",
          "md5": "d0f34cf9e264a3cb19a9c14b3993c56a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.3.2-sources.jar",
          "url": "spring-boot-test-3.3.2-sources.jar",
          "size": 171846,
          "sha512": "07eef4ebc8720ba5c816df0af561f709724b6b81e63d02dc5d42ec313c450a6cf54244be1a70a7f6ecd9ef421edb628a3170c77ab3a192b9a03c24b2333dac39",
          "sha256": "410f0c8af3210a2961a398bd0ac07a5f558bfbdaa3408233477e0f9937471dc2",
          "sha1": "3c220a79e21069bec335835c61e58c5ed01e87a7",
          "md5": "f6449c617be49259826d1b37299ebf56"
        }
      ]
    }
  ]
}
